CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS audio_objects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket          TEXT NOT NULL,
    object_key      TEXT NOT NULL,
    kind            TEXT NOT NULL,
    visibility      TEXT NOT NULL CHECK (visibility IN ('public', 'private')),
    content_sha256  TEXT NOT NULL,
    size_bytes      BIGINT NOT NULL CHECK (size_bytes >= 0),
    mime_type       TEXT NOT NULL,
    metadata_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
    owner_user_id   BIGINT,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (bucket, object_key)
);

CREATE TABLE IF NOT EXISTS users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             TEXT NOT NULL UNIQUE,
    name              TEXT NOT NULL DEFAULT '',
    password_hash     TEXT NOT NULL,
    goal_level        TEXT NOT NULL DEFAULT 'N5' CHECK (goal_level IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    jlpt_levels       TEXT[] NOT NULL DEFAULT ARRAY['N5']::text[],
    streak_days       INTEGER NOT NULL DEFAULT 0 CHECK (streak_days >= 0),
    daily_goals_json  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE audio_objects
    ADD CONSTRAINT fk_audio_objects_owner_user
    FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token       TEXT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ NOT NULL,
    used        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user ON password_reset_tokens(user_id);

CREATE TABLE IF NOT EXISTS words (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kanji_form       TEXT NOT NULL,
    reading          TEXT NOT NULL,
    part_of_speech   TEXT NOT NULL DEFAULT '',
    meaning          TEXT NOT NULL,
    jlpt_level       TEXT NOT NULL CHECK (jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    reading_type     TEXT NOT NULL DEFAULT '',
    audio_object_id  BIGINT REFERENCES audio_objects(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (kanji_form, reading)
);

CREATE INDEX IF NOT EXISTS idx_words_jlpt_level ON words(jlpt_level);
CREATE INDEX IF NOT EXISTS idx_words_audio_object_id ON words(audio_object_id);

CREATE TABLE IF NOT EXISTS word_examples (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id          BIGINT NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    position         INTEGER NOT NULL CHECK (position >= 0),
    japanese         TEXT NOT NULL,
    chinese          TEXT NOT NULL,
    furigana_html    TEXT NOT NULL DEFAULT '',
    audio_object_id  BIGINT REFERENCES audio_objects(id) ON DELETE SET NULL,
    UNIQUE (word_id, position)
);

CREATE INDEX IF NOT EXISTS idx_word_examples_word_id ON word_examples(word_id);
CREATE INDEX IF NOT EXISTS idx_word_examples_audio_object_id ON word_examples(audio_object_id);

CREATE TABLE IF NOT EXISTS word_records (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    word_id              BIGINT NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    mastery_level        INTEGER NOT NULL DEFAULT 0 CHECK (mastery_level >= 0),
    next_review_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    ease_factor          DOUBLE PRECISION NOT NULL DEFAULT 2.5 CHECK (ease_factor > 0),
    interval_days        INTEGER NOT NULL DEFAULT 0 CHECK (interval_days >= 0),
    review_history_json  JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, word_id)
);

CREATE INDEX IF NOT EXISTS idx_word_records_due ON word_records(user_id, next_review_at);
CREATE INDEX IF NOT EXISTS idx_word_records_word_id ON word_records(word_id);

CREATE TABLE IF NOT EXISTS word_review_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    word_id        BIGINT NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    rating         TEXT NOT NULL CHECK (rating IN ('easy', 'normal', 'hard')),
    score          INTEGER NOT NULL DEFAULT 0,
    event_json     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_word_review_events_word_history ON word_review_events(user_id, word_id, created_at DESC);

CREATE TABLE IF NOT EXISTS word_bookmarks (
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    word_id      BIGINT NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, word_id)
);

CREATE INDEX IF NOT EXISTS idx_word_bookmarks_word_id ON word_bookmarks(word_id);

CREATE TABLE IF NOT EXISTS grammar_points (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 TEXT NOT NULL,
    meaning              TEXT NOT NULL,
    conjunction_rule     TEXT NOT NULL DEFAULT '',
    usage_note           TEXT NOT NULL DEFAULT '',
    jlpt_level           TEXT NOT NULL CHECK (jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (name, jlpt_level),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_grammar_points_jlpt ON grammar_points(jlpt_level);

CREATE TABLE IF NOT EXISTS grammar_examples (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grammar_point_id  BIGINT NOT NULL REFERENCES grammar_points(id) ON DELETE CASCADE,
    position          INTEGER NOT NULL CHECK (position >= 0),
    japanese          TEXT NOT NULL,
    chinese           TEXT NOT NULL,
    furigana_html     TEXT NOT NULL DEFAULT '',
    linked_word_ids   BIGINT[] NOT NULL DEFAULT ARRAY[]::bigint[],
    audio_object_id   BIGINT REFERENCES audio_objects(id) ON DELETE SET NULL,
    UNIQUE (grammar_point_id, position)
);

CREATE INDEX IF NOT EXISTS idx_grammar_examples_point_id ON grammar_examples(grammar_point_id);
CREATE INDEX IF NOT EXISTS idx_grammar_examples_audio_object_id ON grammar_examples(audio_object_id);
CREATE INDEX IF NOT EXISTS idx_grammar_examples_linked_word_ids ON grammar_examples USING GIN (linked_word_ids);

CREATE TABLE IF NOT EXISTS grammar_quiz_questions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grammar_point_id  BIGINT NOT NULL REFERENCES grammar_points(id) ON DELETE CASCADE,
    position          INTEGER NOT NULL CHECK (position >= 0),
    type              TEXT NOT NULL CHECK (type IN ('fill_blank', 'multi_choice')),
    prompt            TEXT NOT NULL,
    options           JSONB NOT NULL DEFAULT '[]'::jsonb,
    answer            TEXT NOT NULL,
    explanation       TEXT NOT NULL DEFAULT '',
    UNIQUE (grammar_point_id, position)
);

CREATE INDEX IF NOT EXISTS idx_grammar_quiz_questions_point_id ON grammar_quiz_questions(grammar_point_id);

CREATE TABLE IF NOT EXISTS grammar_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    grammar_point_id    BIGINT NOT NULL REFERENCES grammar_points(id) ON DELETE CASCADE,
    status              TEXT NOT NULL DEFAULT 'unlearned' CHECK (status IN ('unlearned', 'learning', 'mastered')),
    next_review_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    quiz_history_json   JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, grammar_point_id)
);

CREATE INDEX IF NOT EXISTS idx_grammar_records_due ON grammar_records(user_id, next_review_at);
CREATE INDEX IF NOT EXISTS idx_grammar_records_grammar_point_id ON grammar_records(grammar_point_id);

CREATE TABLE IF NOT EXISTS grammar_quiz_attempts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    grammar_point_id  BIGINT NOT NULL REFERENCES grammar_points(id) ON DELETE CASCADE,
    score             INTEGER NOT NULL DEFAULT 0,
    attempt_json      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_grammar_quiz_attempts_history ON grammar_quiz_attempts(user_id, grammar_point_id, created_at DESC);

CREATE TABLE IF NOT EXISTS lessons (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            TEXT NOT NULL,
    jlpt_level       TEXT NOT NULL CHECK (jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    tags             TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
    audio_object_id  BIGINT REFERENCES audio_objects(id) ON DELETE SET NULL,
    char_count       INTEGER NOT NULL DEFAULT 0 CHECK (char_count >= 0),
    shadowing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    shadowing_version INTEGER NOT NULL DEFAULT 1 CHECK (shadowing_version >= 1),
    shadowing_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (title, jlpt_level)
);

CREATE INDEX IF NOT EXISTS idx_lessons_jlpt ON lessons(jlpt_level);
CREATE INDEX IF NOT EXISTS idx_lessons_tags ON lessons USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_lessons_audio_object_id ON lessons(audio_object_id);

ALTER TABLE lessons
    ADD COLUMN IF NOT EXISTS shadowing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS shadowing_version INTEGER NOT NULL DEFAULT 1 CHECK (shadowing_version >= 1),
    ADD COLUMN IF NOT EXISTS shadowing_config_json JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS lesson_sentences (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id  BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    position   INTEGER NOT NULL CHECK (position >= 0),
    tokens     JSONB NOT NULL DEFAULT '[]'::jsonb,
    chinese    TEXT NOT NULL DEFAULT '',
    start_ms   BIGINT NOT NULL DEFAULT 0 CHECK (start_ms >= 0),
    end_ms     BIGINT NOT NULL DEFAULT 0 CHECK (end_ms >= start_ms),
    UNIQUE (lesson_id, position)
);

CREATE INDEX IF NOT EXISTS idx_lesson_sentences_lesson_id ON lesson_sentences(lesson_id);

CREATE TABLE IF NOT EXISTS lesson_words (
    lesson_id   BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    word_id     BIGINT NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    position    INTEGER NOT NULL CHECK (position >= 0),
    PRIMARY KEY (lesson_id, position)
);

CREATE INDEX IF NOT EXISTS idx_lesson_words_word_id ON lesson_words(word_id);

CREATE TABLE IF NOT EXISTS lesson_shadowing_progress (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id            BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    shadowing_version    INTEGER NOT NULL DEFAULT 1 CHECK (shadowing_version >= 1),
    last_sentence_index  INTEGER NOT NULL DEFAULT 0 CHECK (last_sentence_index >= 0),
    last_position_ms     BIGINT NOT NULL DEFAULT 0 CHECK (last_position_ms >= 0),
    last_practice_mode   TEXT NOT NULL DEFAULT 'normal',
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, lesson_id, shadowing_version)
);

CREATE TABLE IF NOT EXISTS lesson_shadowing_attempts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id            BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    shadowing_version    INTEGER NOT NULL DEFAULT 1 CHECK (shadowing_version >= 1),
    sentence_index       INTEGER NOT NULL CHECK (sentence_index >= 0),
    practice_mode        TEXT NOT NULL,
    playback_rate        DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (playback_rate > 0),
    loop_count           INTEGER NOT NULL DEFAULT 0 CHECK (loop_count >= 0),
    self_score           INTEGER CHECK (self_score IS NULL OR (self_score BETWEEN 0 AND 100)),
    recognition_text     TEXT NOT NULL DEFAULT '',
    audio_object_id      BIGINT REFERENCES audio_objects(id) ON DELETE SET NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lesson_shadowing_attempts_sentence
    ON lesson_shadowing_attempts(user_id, lesson_id, shadowing_version, sentence_index, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lesson_shadowing_attempts_history
    ON lesson_shadowing_attempts(user_id, lesson_id, shadowing_version, created_at DESC);

CREATE TABLE IF NOT EXISTS speaking_materials (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             TEXT NOT NULL CHECK (type IN ('shadow', 'free')),
    title            TEXT NOT NULL DEFAULT '',
    text             TEXT NOT NULL,
    lines            TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
    jlpt_level       TEXT NOT NULL CHECK (jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    audio_object_id  BIGINT REFERENCES audio_objects(id) ON DELETE SET NULL,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_speaking_materials_type_level ON speaking_materials(type, jlpt_level);
CREATE INDEX IF NOT EXISTS idx_speaking_materials_audio_object_id ON speaking_materials(audio_object_id);

CREATE TABLE IF NOT EXISTS speaking_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type              TEXT NOT NULL CHECK (type IN ('shadow', 'free')),
    material_id       BIGINT NOT NULL REFERENCES speaking_materials(id) ON DELETE CASCADE,
    score             INTEGER NOT NULL DEFAULT 0 CHECK (score >= 0 AND score <= 100),
    audio_object_id   BIGINT REFERENCES audio_objects(id) ON DELETE SET NULL,
    audio_ref_legacy  TEXT NOT NULL DEFAULT '',
    practiced_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_speaking_records_user ON speaking_records(user_id, practiced_at DESC);
CREATE INDEX IF NOT EXISTS idx_speaking_records_material_id ON speaking_records(material_id);
CREATE INDEX IF NOT EXISTS idx_speaking_records_audio_object_id ON speaking_records(audio_object_id);

CREATE TABLE IF NOT EXISTS writing_questions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type              TEXT NOT NULL CHECK (type IN ('input', 'sentence')),
    prompt            TEXT NOT NULL,
    expected_answer   TEXT NOT NULL,
    grammar_point_id  BIGINT REFERENCES grammar_points(id) ON DELETE SET NULL,
    jlpt_level        TEXT NOT NULL DEFAULT 'N5' CHECK (jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_writing_questions_grammar_point_id ON writing_questions(grammar_point_id);

CREATE TABLE IF NOT EXISTS writing_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type              TEXT NOT NULL CHECK (type IN ('input', 'sentence')),
    question          TEXT NOT NULL,
    user_answer       TEXT NOT NULL DEFAULT '',
    ai_feedback_json  JSONB NOT NULL DEFAULT 'null'::jsonb,
    score             INTEGER NOT NULL DEFAULT 0,
    practiced_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_writing_records_user ON writing_records(user_id, practiced_at DESC);

CREATE TABLE IF NOT EXISTS translation_sources (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          TEXT NOT NULL,
    source_type    TEXT NOT NULL CHECK (source_type IN ('manual', 'url', 'api')),
    source_url     TEXT NOT NULL DEFAULT '',
    api_endpoint   TEXT NOT NULL DEFAULT '',
    raw_content    TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS translation_sentences (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id              BIGINT NOT NULL REFERENCES translation_sources(id) ON DELETE CASCADE,
    direction              TEXT NOT NULL CHECK (direction IN ('cn2jp', 'jp2cn')),
    source_text            TEXT NOT NULL,
    reference_translation  TEXT NOT NULL DEFAULT '',
    position               INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_id, position)
);

CREATE INDEX IF NOT EXISTS idx_translation_sentences_source ON translation_sentences(source_id);

CREATE TABLE IF NOT EXISTS translation_records (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sentence_id                     BIGINT NOT NULL REFERENCES translation_sentences(id) ON DELETE CASCADE,
    user_translation                TEXT NOT NULL,
    score                           INTEGER NOT NULL DEFAULT 0,
    rule_score                      INTEGER NOT NULL DEFAULT 0,
    ai_feedback_json                JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_text_snapshot            TEXT NOT NULL,
    direction_snapshot              TEXT NOT NULL CHECK (direction_snapshot IN ('cn2jp', 'jp2cn')),
    reference_translation_snapshot  TEXT NOT NULL DEFAULT '',
    position_snapshot               INTEGER NOT NULL CHECK (position_snapshot >= 0),
    practiced_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_translation_records_user ON translation_records(user_id);
CREATE INDEX IF NOT EXISTS idx_translation_records_sentence ON translation_records(sentence_id);

CREATE OR REPLACE FUNCTION translation_sentences_immutable_if_practiced()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM translation_records tr
        WHERE tr.sentence_id = OLD.id
        LIMIT 1
    ) AND (
        NEW.source_text IS DISTINCT FROM OLD.source_text OR
        NEW.direction IS DISTINCT FROM OLD.direction OR
        NEW.position IS DISTINCT FROM OLD.position
    ) THEN
        RAISE EXCEPTION 'cannot mutate practiced translation sentence %', OLD.id;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_translation_sentences_immutable_prompt ON translation_sentences;
CREATE TRIGGER trg_translation_sentences_immutable_prompt
BEFORE UPDATE ON translation_sentences
FOR EACH ROW
EXECUTE PROCEDURE translation_sentences_immutable_if_practiced();

CREATE TABLE IF NOT EXISTS notes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type                 TEXT NOT NULL CHECK (type IN ('word', 'grammar', 'sentence')),
    title                TEXT NOT NULL,
    content              TEXT NOT NULL DEFAULT '',
    source_text          TEXT NOT NULL DEFAULT '',
    reference_id         BIGINT,
    reference_type       TEXT,
    tags                 TEXT[] NOT NULL DEFAULT ARRAY[]::text[],
    mastery_level        INTEGER NOT NULL DEFAULT 0 CHECK (mastery_level >= 0),
    next_review_at       TIMESTAMPTZ,
    ease_factor          DOUBLE PRECISION NOT NULL DEFAULT 2.5 CHECK (ease_factor > 0),
    interval_days        INTEGER NOT NULL DEFAULT 0 CHECK (interval_days >= 0),
    review_history_json  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at           TIMESTAMPTZ,
    CHECK (
        (reference_id IS NULL AND reference_type IS NULL) OR
        (reference_id IS NOT NULL AND reference_type IN ('word', 'grammar'))
    )
);

CREATE INDEX IF NOT EXISTS idx_notes_user_id ON notes(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_type ON notes(user_id, type);
CREATE INDEX IF NOT EXISTS idx_notes_review ON notes(user_id, next_review_at) WHERE next_review_at IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_notes_reference ON notes(reference_type, reference_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_notes_tags ON notes USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_notes_search_title ON notes USING GIN (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_notes_search_content ON notes USING GIN (content gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_notes_search_source_text ON notes USING GIN (source_text gin_trgm_ops);

CREATE TABLE IF NOT EXISTS note_links (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    note_id         BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    target_note_id  BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    relation        TEXT NOT NULL DEFAULT 'related',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (note_id, target_note_id)
);

CREATE INDEX IF NOT EXISTS idx_note_links_note_id ON note_links(note_id);
CREATE INDEX IF NOT EXISTS idx_note_links_target_note_id ON note_links(target_note_id);

CREATE TABLE IF NOT EXISTS note_review_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    note_id      BIGINT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    rating       TEXT NOT NULL CHECK (rating IN ('easy', 'normal', 'hard')),
    event_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_note_review_events_note_history ON note_review_events(user_id, note_id, created_at DESC);

CREATE TABLE IF NOT EXISTS study_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        TEXT NOT NULL UNIQUE,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    module            TEXT NOT NULL CHECK (module IN ('word', 'grammar', 'lesson', 'speaking', 'writing', 'translation')),
    duration_seconds  INTEGER NOT NULL DEFAULT 0 CHECK (duration_seconds >= 0),
    completed_count   INTEGER NOT NULL DEFAULT 0 CHECK (completed_count >= 0),
    started_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_study_sessions_user ON study_sessions(user_id, started_at DESC);

CREATE TABLE IF NOT EXISTS session_summaries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          TEXT NOT NULL UNIQUE REFERENCES study_sessions(session_id) ON DELETE CASCADE,
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    module              TEXT NOT NULL CHECK (module IN ('word', 'grammar', 'lesson', 'speaking', 'writing', 'translation')),
    score_summary_json  JSONB NOT NULL DEFAULT '{}'::jsonb,
    strengths_json      JSONB NOT NULL DEFAULT '[]'::jsonb,
    weaknesses_json     JSONB NOT NULL DEFAULT '[]'::jsonb,
    suggestions_json    JSONB NOT NULL DEFAULT '[]'::jsonb,
    generated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_session_summaries_user_generated_at ON session_summaries(user_id, generated_at DESC);
