ALTER TABLE lessons
    ADD COLUMN IF NOT EXISTS shadowing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS shadowing_version INTEGER NOT NULL DEFAULT 1 CHECK (shadowing_version >= 1),
    ADD COLUMN IF NOT EXISTS shadowing_config_json JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS lesson_shadowing_progress (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id            BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    shadowing_version    INTEGER NOT NULL DEFAULT 1 CHECK (shadowing_version >= 1),
    last_sentence_index  INTEGER NOT NULL DEFAULT 0 CHECK (last_sentence_index >= 0),
    last_position_ms     BIGINT NOT NULL DEFAULT 0 CHECK (last_position_ms >= 0),
    last_practice_mode   TEXT NOT NULL DEFAULT 'normal',
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, lesson_id, shadowing_version)
);

CREATE TABLE IF NOT EXISTS lesson_shadowing_attempts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lesson_id            BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    shadowing_version    INTEGER NOT NULL DEFAULT 1 CHECK (shadowing_version >= 1),
    sentence_index       INTEGER NOT NULL CHECK (sentence_index >= 0),
    practice_mode        TEXT NOT NULL,
    playback_rate        DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (playback_rate > 0),
    loop_count           INTEGER NOT NULL DEFAULT 0 CHECK (loop_count >= 0),
    self_score           INTEGER CHECK (self_score IS NULL OR (self_score BETWEEN 0 AND 100)),
    recognition_text     TEXT NOT NULL DEFAULT '',
    audio_ref            TEXT NOT NULL DEFAULT '',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lesson_shadowing_attempts_sentence
    ON lesson_shadowing_attempts(user_id, lesson_id, shadowing_version, sentence_index, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lesson_shadowing_attempts_history
    ON lesson_shadowing_attempts(user_id, lesson_id, shadowing_version, created_at DESC);
