CREATE TABLE IF NOT EXISTS video_objects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket          TEXT NOT NULL,
    object_key      TEXT NOT NULL,
    kind            TEXT NOT NULL,
    visibility      TEXT NOT NULL CHECK (visibility IN ('public', 'private')),
    content_sha256  TEXT NOT NULL,
    size_bytes      BIGINT NOT NULL CHECK (size_bytes >= 0),
    mime_type       TEXT NOT NULL,
    metadata_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
    owner_user_id   BIGINT REFERENCES users(id) ON DELETE CASCADE,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (bucket, object_key)
);

CREATE INDEX IF NOT EXISTS idx_video_objects_owner_user_id ON video_objects(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_video_objects_kind ON video_objects(kind);

ALTER TABLE lessons
    ADD COLUMN IF NOT EXISTS video_object_id BIGINT REFERENCES video_objects(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_lessons_video_object_id ON lessons(video_object_id);
